### ISSUE TITLE
Color Picker - shows error when extending the controller

### ISSUE THREAD

**Issue by remy727** [stimulus-components/stimulus-components#122]
## Error
```
application-7bc7172f2d42f6f19cf72fe6c44891d5ca59c42867c6675dec9378245e464141.js:12555 Error connecting controller

Error: Missing target element "button" for "polaris--color-picker" controller
    at extended.get (application-7bc7172f2d42f6f19cf72fe6c44891d5ca59c42867c6675dec9378245e464141.js:12684:19)
    at extended.connect (application-7bc7172f2d42f6f19cf72fe6c44891d5ca59c42867c6675dec9378245e464141.js:22360:24)
    at Context.connect (application-7bc7172f2d42f6f19cf72fe6c44891d5ca59c42867c6675dec9378245e464141.js:11938:25)
    at Module.connectContextForScope (application-7bc7172f2d42f6f19cf72fe6c44891d5ca59c42867c6675dec9378245e464141.js:12102:15)
    at Router.scopeConnected (application-7bc7172f2d42f6f19cf72fe6c44891d5ca59c42867c6675dec9378245e464141.js:12463:16)
    at ScopeObserver.elementMatchedValue (application-7bc7172f2d42f6f19cf72fe6c44891d5ca59c42867c6675dec9378245e464141.js:12380:23)
    at ValueListObserver.tokenMatched (application-7bc7172f2d42f6f19cf72fe6c44891d5ca59c42867c6675dec9378245e464141.js:11516:23)
    at TokenListObserver.tokenMatched (application-7bc7172f2d42f6f19cf72fe6c44891d5ca59c42867c6675dec9378245e464141.js:11453:21)
    at application-7bc7172f2d42f6f19cf72fe6c44891d5ca59c42867c6675dec9378245e464141.js:11447:38
    at Array.forEach (<anonymous>)

{identifier: 'polaris--color-picker', controller: extended, element: div}
```

### HTML
```html
<div data-controller="polaris--color-picker">
  <input type="hidden" name="color" value="#667EEA" data-polaris--color-picker-target="input" />

  <div data-polaris--color-picker-target="button"></div>
</div>
```

### Stimulus JS
```js
import ColorPicker from '@stimulus-components/color-picker'

// Connects to data-controller="polaris--color-picker"
export default class extends ColorPicker {
  connect() {
    super.connect() // raises error

    console.log(this.buttonTarget)
    // Pickr instance
    this.picker
  }
}
```

**Comment by guillaumebriday** [comment]
Hmm, just tried in the live preview docs and everything works just fine:

```html
<script type="module">
  import "../app.css"
  import { Application } from "@hotwired/stimulus"
  import ColorPicker from "./src/index"
  import "@simonwep/pickr/dist/themes/classic.min.css"
  import "@simonwep/pickr/dist/themes/monolith.min.css"
  import "@simonwep/pickr/dist/themes/nano.min.css"

  class PolarisColorPicker extends ColorPicker {
    connect( ) {
      super.connect()

      console.log(this.picker)
    }
  }

  const application = Application.start()
  application.register("polaris--color-picker", PolarisColorPicker)
</script>

<div data-controller="polaris--color-picker">
  <label>Classic</label>
  <input type="hidden" name="color" value="#F56565" data-polaris--color-picker-target="input" />

  <div data-polaris--color-picker-target="button"></div>
</div>
```

Are you sure that your controller is properly registered?

**Comment by guillaumebriday** [comment]
Please reopen if needed 👍

**Comment by remy727** [comment]
I am very sorry for the late reply. I was off for personal reasons. I confirmed I didn't see any error. Thank you for your support!
